
title: My Personal Website
url: 'http://junlulocky.com'
baseurl: 'https://jchen9314.github.io/PanelCV/' #change it according to your repository name



# Profile information
yourname: Jason Chen  ## put your name
title: 'Data Science | Machine Learning | Statistics | Big Data'  ## your title
location: Toronto, ON


## Social Profiles
github: https://github.com/jchen9314
facebook: https://www.facebook.com/profile.php?id=100004224133848  ## your facebook account url
twitter: https://twitter.com/JasonCh50918329  ## your twitter account url
linkedin: https://www.linkedin.com/in/jasonjychen ## your linkedin account url

youtube: http://www.youtube.com  ## you dribbble account url
# foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
